name: Test

on:
  push:

jobs:
  prove:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-14', 'macos-13']
        perl: [ '5.38', '5.36', '5.34', '5.32', '5.30' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - name: Setup Perl environment
        uses: shogo82148/actions-setup-perl@v1
      - uses: actions/checkout@v2
      - run: cpanm -q --notest --no-man-pages --installdeps .
      - run: yath test
